### ISSUE TITLE
Can't use `pyopenephys` with more than one `events` folders

### ISSUE THREAD

**Issue by weiglszonja** [CINPLA/pyopenephys#40]
@alejoe91 I have binary data with more than 1 events folder as pointed out in linked issue:
https://github.com/catalystneuro/neuroconv/issues/969
But I'm receiving an error from `pyopenephys` :

```python-traceback
Traceback (most recent call last):
  File "/Users/weian/anaconda3/envs/constantinople-lab-to-nwb/lib/python3.11/site-packages/neuroconv/datainterfaces/ecephys/openephys/openephysbinarydatainterface.py", line 94, in __init__
    raise error
  File "/Users/weian/anaconda3/envs/constantinople-lab-to-nwb/lib/python3.11/site-packages/neuroconv/datainterfaces/ecephys/openephys/openephysbinarydatainterface.py", line 79, in __init__
    _open_with_pyopenephys(folder_path=folder_path)
  File "/Users/weian/anaconda3/envs/constantinople-lab-to-nwb/lib/python3.11/site-packages/neuroconv/datainterfaces/ecephys/openephys/openephysbinarydatainterface.py", line 18, in _open_with_pyopenephys
    pyopenephys_file = pyopenephys.File(foldername=folder_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/weian/anaconda3/envs/constantinople-lab-to-nwb/lib/python3.11/site-packages/pyopenephys/core.py", line 175, in __init__
    self._experiments.append(Experiment(op.join(self._absolute_foldername, rel_path), id, self))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/weian/anaconda3/envs/constantinople-lab-to-nwb/lib/python3.11/site-packages/pyopenephys/core.py", line 263, in __init__
    Recording(op.join(self._absolute_foldername, rel_path), id, self, verbose=verbose)
  File "/Users/weian/anaconda3/envs/constantinople-lab-to-nwb/lib/python3.11/site-packages/pyopenephys/core.py", line 425, in __init__
    raise Exception("More than one events folder found!")
Exception: More than one events folder found!
```
I'm not that familiar with the binary format, would it be possible to make this work with more event folders?

**Comment by alejoe91** [comment]
This has been handled directly in neuroconv since `pyopenephys` is only used to parse the `session_start_time`
